<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <AssemblyName>BackupDatabase</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VetBackup.Shared\VetBackup.Shared.csproj" />
  </ItemGroup>

</Project>
